# Feature Engineering

In [2]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
import numpy as np
from nltk.corpus import stopwords
import re
import json
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score

from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

### Text Cleaning

In [3]:
books = pd.read_csv('../data/booksummaries/data.csv')
books.head()
genres = []
for i in books['genre']:
    genres.append(list(json.loads(i).values()))
books['genre_new'] = genres

In [4]:
def clean_summary(text):
    text = re.sub("\'", "", text)
    text = re.sub("[^a-zA-Z]"," ",text)
    text = ' '.join(text.split())
    text = text.lower()
    return text

In [5]:
books['clean_summary'] = books['summary'].apply(lambda x: clean_summary(x))
books.head(2)

,book_id,book_name,genre,summary,genre_new,clean_summary
0,620,Animal Farm,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...
1,843,A Clockwork Orange,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...

In [6]:
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    no_stopword_text = [w for w in text.split() if not w in stop_words]
    return ' '.join(no_stopword_text)

books['clean_summary'] = books['clean_summary'].apply(lambda x: remove_stopwords(x))

In [7]:
books['clean_summary'][0]

'old major old boar manor farm calls animals farm meeting compares humans parasites teaches animals revolutionary song beasts england major dies two young pigs snowball napoleon assume command turn dream philosophy animals revolt drive drunken irresponsible mr jones farm renaming animal farm adopt seven commandments animal ism important animals equal snowball attempts teach animals reading writing food plentiful farm runs smoothly pigs elevate positions leadership set aside special food items ostensibly personal health napoleon takes pups farm dogs trains privately napoleon snowball struggle leadership snowball announces plans build windmill napoleon dogs chase snowball away declares leader napoleon enacts changes governance structure farm replacing meetings committee pigs run farm using young pig named squealer mouthpiece napoleon claims credit windmill idea animals work harder promise easier lives windmill violent storm animals find windmill annihilated napoleon squealer convince animals snowball destroyed although scorn neighbouring farmers suggests walls thin snowball becomes scapegoat napoleon begins purging farm dogs killing animals accuses consorting old rival pigs abuse power imposing control reserving privileges rewriting history villainising snowball glorifying napoleon squealer justifies every statement napoleon makes even pigs alteration seven commandments animalism benefit beasts england replaced anthem glorifying napoleon appears adopting lifestyle man animals remain convinced better mr jones squealer abuses animals poor memories invents numbers show improvement mr frederick one neighbouring farmers attacks farm using blasting powder blow restored windmill though animals win battle great cost many including boxer workhorse wounded despite injuries boxer continues working harder harder collapses working windmill napoleon sends van take boxer veterinary surgeons explaining better care given benjamin cynical donkey could read well pig notices van belongs knacker attempts mount rescue animals attempts futile squealer reports van purchased hospital writing previous owner repainted recounts tale boxers death hands best medical care years pass pigs learn walk upright carry whips wear clothes seven commandments reduced single phrase animals equal animals equal others napoleon holds dinner party pigs humans area congratulate napoleon hardest working least fed animals country napoleon announces alliance humans labouring classes worlds abolishes practices traditions related revolution changes name farm manor farm animals overhearing conversation notice faces pigs begun changing poker match argument breaks napoleon mr pilkington animals realise faces pigs look like faces humans one tell difference pigs snowball napoleon squealer adapt old majors ideas actual philosophy formally name animalism soon napoleon squealer indulge vices humans drinking alcohol sleeping beds trading squealer employed alter seven commandments account humanisation allusion soviet governments revising history order exercise control peoples beliefs society original commandments whatever goes upon two legs enemy whatever goes upon four legs wings friend animal shall wear clothes animal shall sleep bed animal shall drink alcohol animal shall kill animal animals equal later napoleon pigs secretly revise commandments clear accusations law breaking animal shall drink alcohol excess appended animal shall sleep bed sheets added changed commandments follows changes bolded animal shall sleep bed sheets animal shall drink alcohol excess animal shall kill animal without cause eventually replaced maxims animals equal animals equal others four legs good two legs better pigs become human ironic twist original purpose seven commandments supposed keep order within animal farm uniting animals together humans prevent animals following humans evil habits revision commandments orwell demonstrates simply political dogma turned malleable propaganda'

### Remove all labels that you can find less than 100 times

In [8]:
dict = {}
for index, row in books.iterrows():
    for x in row['genre_new']:
        if x in dict:
            dict[x] = dict[x] +1
        else:
            dict[x] = 1

dict.get("Fiction")
books.head()

,book_id,book_name,genre,summary,genre_new,clean_summary
0,620,Animal Farm,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[Roman à clef, Satire, Children's literature, ...",old major old boar manor farm calls animals fa...
1,843,A Clockwork Orange,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[Science Fiction, Novella, Speculative fiction...",alex teenager living near future england leads...
2,986,The Plague,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...,"[Existentialism, Fiction, Absurdist fiction, N...",text plague divided five parts town oran thous...
3,2080,A Fire Upon the Deep,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...,"[Hard science fiction, Science Fiction, Specul...",novel posits space around milky way divided co...
4,2152,All Quiet on the Western Front,"{""/m/098tmk"": ""War novel"", ""/m/016lj8"": ""Roman...","The book tells the story of Paul Bäumer, a Ge...","[War novel, Roman à clef]",book tells story paul b umer german soldier ur...

In [9]:
def getGenresInMoreThan100Books(row):
    genres = []
    for x in row:
        if dict[x] > 100:
            genres.append(x)
    return genres

In [10]:
books['genre_new'] = books['genre_new'].apply(lambda x: getGenresInMoreThan100Books(x))
books.head()

,book_id,book_name,genre,summary,genre_new,clean_summary
0,620,Animal Farm,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[Satire, Children's literature, Speculative fi...",old major old boar manor farm calls animals fa...
1,843,A Clockwork Orange,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[Science Fiction, Speculative fiction, Satire,...",alex teenager living near future england leads...
2,986,The Plague,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...,"[Fiction, Novel]",text plague divided five parts town oran thous...
3,2080,A Fire Upon the Deep,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...,"[Science Fiction, Speculative fiction, Fantasy...",novel posits space around milky way divided co...
4,2152,All Quiet on the Western Front,"{""/m/098tmk"": ""War novel"", ""/m/016lj8"": ""Roman...","The book tells the story of Paul Bäumer, a Ge...",[],book tells story paul b umer german soldier ur...

In [11]:
books['most_common_genres'] = books['genre_new'].apply(lambda x: json.dumps(x))
books.head()

,book_id,book_name,genre,summary,genre_new,clean_summary,most_common_genres
0,620,Animal Farm,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[Satire, Children's literature, Speculative fi...",old major old boar manor farm calls animals fa...,"[""Satire"", ""Children's literature"", ""Speculati..."
1,843,A Clockwork Orange,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[Science Fiction, Speculative fiction, Satire,...",alex teenager living near future england leads...,"[""Science Fiction"", ""Speculative fiction"", ""Sa..."
2,986,The Plague,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...,"[Fiction, Novel]",text plague divided five parts town oran thous...,"[""Fiction"", ""Novel""]"
3,2080,A Fire Upon the Deep,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...,"[Science Fiction, Speculative fiction, Fantasy...",novel posits space around milky way divided co...,"[""Science Fiction"", ""Speculative fiction"", ""Fa..."
4,2152,All Quiet on the Western Front,"{""/m/098tmk"": ""War novel"", ""/m/016lj8"": ""Roman...","The book tells the story of Paul Bäumer, a Ge...",[],book tells story paul b umer german soldier ur...,[]

### Label Encoding

### Split data

In [12]:
books.head()
#books.head()
df2 = (books.drop(columns='genre_new').join(books['genre_new'].str.join('|').str.get_dummies()))
#xtrain, xval, ytrain, yval = train_test_split(books['clean_summary'], np.array(books['most_common_genres']), test_size=0.2, random_state=557)
#type(yval[0])
#df2.head()

In [13]:
y = np.asarray(df2[df2.columns[7:]])
X = df2["clean_summary"]
# initializing TfidfVectorizer 
  
# splitting the data to training and testing data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
  
# transforming the data
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=10000)

xtrain_tfidf = tfidf_vectorizer.fit_transform(X_train.values.astype('U'))

xval_tfidf = tfidf_vectorizer.transform(X_test.values.astype('U'))

In [14]:
y_test[11]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0])

In [15]:
def hamming_score(y_true, y_pred, normalize=True, sample_weight=None):
    '''
    Compute the Hamming score (a.k.a. label-based accuracy) for the multi-label case
    http://stackoverflow.com/q/32239577/395857
    '''
    acc_list = []
    for i in range(y_true.shape[0]):
        set_true = set( np.where(y_true[i])[0] )
        set_pred = set( np.where(y_pred[i])[0] )
        #print('\nset_true: {0}'.format(set_true))
        #print('set_pred: {0}'.format(set_pred))
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        #print('tmp_a: {0}'.format(tmp_a))
        acc_list.append(tmp_a)
    return np.mean(acc_list)

In [17]:
lr = LogisticRegression()
clf = OneVsRestClassifier(lr)

# fit model on train data.
clf.fit(xtrain_tfidf, y_train)

# make predictions for validation set.
y_pred_lr = clf.predict(xval_tfidf)


from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
  


#Calculating the accuracy.
print( 'Accuracy Score :',hamming_score(y_test, y_pred_lr) )

from skmultilearn.adapt import MLkNN

classifier = MLkNN(k=20)

# train
classifier.fit(xtrain_tfidf, y_train)

# predict
predictions = classifier.predict(X_test)

# predict
predictions = classifier.predict(X_test)

from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
  


#Calculating the accuracy.
print( 'Accuracy Score :',hamming_score(y_test, y_pred_lr) )

TypeError: __init__() takes 1 positional argument but 2 were given